name: Redis runner example
on: push

jobs:
  # Etiqueta del trabajo del ejecutor
  runner-job:
    # Debes usar un entorno Linux cuando utilices contenedores de servicio o trabajos de contenedor
    runs-on: ubuntu-latest

    # Contenedores de servicio para ejecutar con `runner-job`
    services:
      # Etiqueta usada para acceder al contenedor de servicio
      redis:
        # Imagen de Docker Hub
        image: redis
        # Establece revisiones de estado para esperar hasta que Redis haya comenzado
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Asigna el puerto 6379 en el contenedor de servicio al host
          - 6379:6379

    steps:
      # Descarga una copia del c칩digo en tu repositorio antes de ejecutar pruebas de CI
      - name: Check out repository code
        uses: actions/checkout@v2

      # Realiza una instalaci칩n limpia de todas las dependencias en el archivo `package.json`
      # Para obtener m치s informaci칩n, consulta https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm ci

      - name: Connect to Redis
        # Ejecuta un script que crea un cliente Redis, rellena
        # el cliente con datos y recupera datos
        run: npm run test
        # Variable de entorno utilizada por el script `client.js` para  crear
        # un nuevo cliente Redis.
        env:
          # El nombre del host utilizado para comunicarse con el contenedor del servicio Redis
          REDIS_HOST: localhost
          # El puerto Redis predeterminado
          REDIS_PORT: 6379