name: Redis runner example
on: push

jobs:
  # Etiqueta del trabajo del ejecutor
  runner-job:
    # Debes usar un entorno Linux cuando utilices contenedores de servicio o trabajos de contenedor
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Tests

        run: npm run test
