on: [push, pull_request]
name: Integracion continua con node.js


jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    container:
      image: node
    # Contenedores de servicio para ejecutar con `ci_to_master`
    services:
      redis:  # Etiqueta utilizada para acceder al contenedor de servicio
        # Imagen del contenedor Docker Hub
        image: redis
        # Establece revisiones de estado para esperar hasta que Redis haya comenzado
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: 'clone and checkout'
        uses: actions/checkout@v1
      - name: 'use node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: 'install dependencies'
        run: npm install
      - name: 'npm run tests'
        run: npm test
        env:
          REDIS_URI: ${{ secrets.REDIS_URI }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          PREFIJO_REDIS: ${{ secrets.PREFIJO_REDIS }}
